pipeline {
  agent {
    label "dbp"
  }

  options {        
    ansiColor('xterm')
  }

  environment {
    BRANCH_NAME      = "`echo ${env.GIT_BRANCH}|sed 's/\\\\//_/'`"
    DESIREDNAMESPACE = "${BRANCH_NAME}-${env.BUILD_NUMBER}"
    DNSZONE          = "${DESIREDNAMESPACE}.dev.alfresco.me"
  }

  stages {
    stage('Namespace') {
      steps {
        sh "make update-kubeconfig"        
      }
    }
  }
}
